//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Task
    {
        public int Id { get; set; }
        public string Title { get; set; }

        [AllowHtml]
        public string Description { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
